### ISSUE TITLE
MSTableViewCell.prepareForReuse

### ISSUE THREAD

**Issue by leoyang-sentia** [MaherKSantina/MSAutoView#18]
MSTableViewCell could notify the main view when table view cell has been reused.

**Comment by MaherKSantina** [comment]
@leoyang-sentia thanks for raising this issue! It's a good idea to make the view handle reusing of the cells. Do you think you can make a PR for that?

**Comment by leoyang-sentia** [comment]
yes, I wanted to make a PR for this long time ago. And I will do it one day. Just create an issue here then we won't forget it.

**Comment by MaherKSantina** [comment]
@leoyang-sentia, I made an update for the pod to include this change. Please feel free to open a new issue if you noticed anyhthing 👍
